version: "3.2"
services:
  backend:
    build: ./
    ports:
      - "3000:3000"
    command: npm run start
    depends_on :
      - db
      - redis-cache
    image: prasetiyo28/api-editor
    environment :
      NODE_ENV : local      
      PORT : 3000
      DATABASE_HOST : db
      DATABASE_PORT : 3306
      DATABASE_USER : root
      DATABASE_PASSWORD : ""
      DATABASE_NAME : editor-kompas
      REDIS_HOST : redis-cache
      REDIS_PORT : 6379
      REDIS_PASSWORD : 
  db:
    image: mysql
    environment :
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD:
      MYSQL_DATABASE: editor-kompas
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    ports:
      - "14045:3306"
  redis-cache:
    image: redis
    ports:
      - "6379:6379"